IgnorePath /.snapshots/\*
IgnorePath /var/lib/pacman/\*
IgnorePath /var/lib/sbctl/\*
IgnorePath /var/lib/NetworkManager/\*
IgnorePath /usr/lib/modules/\*
IgnorePath /usr/lib/systemd/\*
IgnorePath /var/lib/systemd/\*
IgnorePath /var/lib/tpm2-tss/\*
IgnorePath /usr/bin/groupmems
IgnorePath /var/log/\*
IgnorePath /etc/ssl/certs/\*
IgnorePath /etc/pacman.d/gnupg/\*
IgnorePath /etc/ca-certificates/\*
IgnorePath /var/tmp/\*
IgnorePath /efi/EFI/\*
IgnorePath /boot/\*
IgnorePath /etc/.pwd.lock
IgnorePath /etc/.updated
IgnorePath /etc/adjtime
IgnorePath /etc/NetworkManager/\*
IgnorePath /etc/kernel/pcr\*
IgnorePath /usr/lib/locale/locale-archive
IgnorePath /usr/lib/udev/hwdb.bin
IgnorePath /usr/share/info/dir
IgnorePath /var/.updated
IgnorePath /var/lib/dbus/machine-id /etc/machine-id
IgnorePath /var/lib/lastlog
IgnorePath /var/lib/libuuid
IgnorePath /var/lib/machines
IgnorePath /var/lib/portables
IgnorePath /var/lib/private
IgnorePath /etc/group
IgnorePath /etc/group-
IgnorePath /etc/gshadow
IgnorePath /etc/gshadow-
IgnorePath /etc/ld.so.cache
IgnorePath /etc/os-release ../usr/lib/os-release
IgnorePath /etc/passwd
IgnorePath /etc/passwd-
IgnorePath /etc/resolv.conf
IgnorePath /etc/fonts/conf.d/\*
IgnorePath /etc/shadow
IgnorePath /etc/shadow-
IgnorePath /etc/shells
IgnorePath /etc/subgid
IgnorePath /etc/subgid-
IgnorePath /etc/subuid
IgnorePath /etc/subuid-
IgnorePath /efi/loader/entries
IgnorePath /efi/loader/entries.srel
IgnorePath /efi/loader/keys
IgnorePath /efi/loader/random-seed
IgnorePath /etc/fonts/conf.d/10-hinting-slight.conf
IgnorePath /usr/lib/\*
IgnorePath /usr/share/glib-2.0/\*
IgnorePath /usr/share/mime/\*
IgnorePath /var/lib/boltd/\*
IgnorePath /var/lib/sddm\* 
IgnorePath /etc/xml/catalog
IgnorePath /usr/share/applications/mimeinfo.cache
IgnorePath /var/lib/colord/\*
IgnorePath /var/lib/mysql
IgnorePath /var/lib/upower/\*
IgnorePath /usr/share/icons/Adwaita/icon-theme.cache
IgnorePath /usr/share/icons/AdwaitaLegacy/icon-theme.cache
IgnorePath /usr/share/icons/hicolor/icon-theme.cache
IgnorePath /var/lib/plocate/plocate.db
