# Systemd
IgnorePathsExcept /var/lib/systemd 'linger' 'linger/*'

# Btrfs snapshots
IgnorePath /.snapshots/\*

# /boot
IgnorePath /boot/\*

# /efi
IgnorePath /efi/EFI/\*
IgnorePath /efi/loader/credentials
IgnorePath /efi/loader/entries
IgnorePath /efi/loader/entries.srel
IgnorePath /efi/loader/keys
IgnorePath /efi/loader/random-seed

# /etc
IgnorePath /etc/adjtime
IgnorePath /etc/audit/\*
IgnorePath /etc/audisp
IgnorePath /etc/ca-certificates/\*
IgnorePath /etc/colord\*
IgnorePath /etc/fonts/conf.d/\*
IgnorePath /etc/group
IgnorePath /etc/group-
IgnorePath /etc/gshadow
IgnorePath /etc/gshadow-
IgnorePath /etc/iscsi/\*
IgnorePath /etc/kernel/pcr\*
IgnorePath /etc/ld.so.cache
IgnorePath /etc/NetworkManager/\*
IgnorePath /etc/os-release
IgnorePath /etc/pacman.d/gnupg/\*
IgnorePath /etc/pacman.d/mirrorlist\*
IgnorePath /etc/passwd
IgnorePath /etc/passwd-
IgnorePath /etc/passwd.OLD
IgnorePath /etc/printcap
IgnorePath /etc/resolv.conf
IgnorePath /etc/shadow
IgnorePath /etc/shadow-
IgnorePath /etc/shells
IgnorePath /etc/ssl/certs/\*
IgnorePath /etc/subgid
IgnorePath /etc/subgid-
IgnorePath /etc/subuid
IgnorePath /etc/subuid-
IgnorePath /etc/texmf/\*
IgnorePath /etc/userdb
IgnorePath /etc/xml/catalog
IgnorePath /etc/wireguard/\*key
IgnorePath /etc/.updated
IgnorePath /etc/.pwd.lock

# /usr
IgnorePath /usr/bin/groupmems
IgnorePath /usr/lib/\*
IgnorePath /usr/lib32/gconv/\*
IgnorePath /usr/lib/locale/locale-archive
IgnorePath /usr/lib/modules/\*
IgnorePath /usr/lib/systemd/\*
IgnorePath /usr/lib/udev/hwdb.bin
IgnorePath /usr/share/applications/mimeinfo.cache
IgnorePath /usr/share/glib-2.0/\*
IgnorePath /usr/share/icons/\*/\*.cache
IgnorePath /usr/share/info/dir
IgnorePath /usr/share/mime/\*
IgnorePath /usr/share/texmf-dist/\*
IgnorePath /usr/share/vim/vimfiles/doc/tags

# /var
IgnorePath /var/db/\*
IgnorePath /var/lib/bluetooth/\*
IgnorePath /var/lib/boltd/\*
IgnorePath /var/lib/btrfs/\*
IgnorePath /var/lib/cni/networks
IgnorePath /var/lib/colord/\*
IgnorePath /var/lib/containers
IgnorePath /var/lib/cvmfs
IgnorePath /var/lib/dbus/machine-id /etc/machine-id
IgnorePath /var/lib/dkms/\*
IgnorePath /var/lib/flatpak/\*
IgnorePath /var/lib/fwupd/\*
IgnorePath /var/lib/lastlog
IgnorePath /var/lib/libuuid
IgnorePath /var/lib/machines
IgnorePath /var/lib/mysql
IgnorePath /var/lib/NetworkManager/\*
IgnorePath /var/lib/openldap/\*
IgnorePath /var/lib/pacman/\*
IgnorePath /var/lib/passim/\*
IgnorePath /var/lib/plasmalogin/\*
IgnorePath /var/lib/plocate/plocate.db
IgnorePath /var/lib/portables
IgnorePath /var/lib/private
IgnorePath /var/lib/sbctl/\*
IgnorePath /var/lib/sddm\*
IgnorePath /var/lib/texmf/\*
IgnorePath /var/lib/tlp/rfkill_saved
IgnorePath /var/lib/tpm2-tss/\*
IgnorePath /var/lib/upower/\*
IgnorePath /var/log/\*
IgnorePath /var/spool/cups/\*
IgnorePath /var/tmp/\*
IgnorePath /var/.updated
